package com.protondevelopers.Factsforyou;

/**
 * Created by Sufi on 1/5/2017.
 */
import java.util.Random;



public class FactBook {

    // Member variables (properties about the object)
    String[] mFacts = {
            "Ants stretch when they wake up in the morning.",
            "Ostriches can run faster than horses.",
            "Olympic gold medals are actually made mostly of silver.",
            "You are born with 300 bones; by the time you are an adult you will have 206.",
            "It takes about 8 minutes for light from the Sun to reach Earth.",
            "Some bamboo plants can grow almost a meter in just one day.",
            "The state of Florida is bigger than England.",
            "Some penguins can leap 2-3 meters out of the water.",
            "On average, it takes 66 days to form a new habit.",
            "Australia has over 10,000 beaches. You could visit a new beach everyday for over 27 years!",
            "It was Nicholas Cage who first advised Johnny Depp to pursue a career in acting, during the mid 1980’s.",
            "Mammoths still walked the earth when the Great Pyramid was being built.",
            "A group of crows is called a murder.",
            "The reason the taste of artificial banana flavouring and artificial banana flavoured products doesn’t taste like bananas is because it is based on a type of banana that was wiped out by a plague in the 1950’s.",
            "The national animal of Scotland is the Unicorn.",
            "The directors of the film Despicable Me actually wrote their own language for the Minions called Minionise.",
            "The mayor of the Alaskan town, Talkeetna, is called Stubbs and has been mayor of the town since July 1997. Stubbs is a cat.",
            "The Nazis were the first ever people in modern history to start an anti-smoking and tobacco movement.",
            "There is an uninhabited island in the Bahamas known as Pig Beach, which is populated entirely by swimming pigs.",
            "If eaten in one meal, 30 to 90 grams of polar bear liver is enough to kill a human being.",
            "In 2002 alone, more people in the U.S. were killed by dogs than in shark attacks in the past 100 years.",
            "American college, Massachusetts Institute of Technology, deems certain students who take courses in Pistol Marksmanship, Archery, Sailing and Fencing as certified ‘Pirates’.",
            "It is predicted that the reason why night insects, such as moths, are attracted to lights is because they mistake them for the light of the moon, which they used to navigate the Earth before mankind made artificial lights.",
            "Hares are born with fur and can see whilst rabbits are born ‘naked’ and blind.",
            "In 2005, Iraqi insurgents tried to convince American officials that they were holding an American soldier hostage and meant to kill him if Iraqi prisoners were not released. However, their supposed hostage turned out to be a military action figure, not an actual soldier.",
            "In the film Star Wars Episode Three: Revenge of the Sith, every single one of the clone troopers was produced using CGI effects.",
            "There is now technology built into some guns in America that allow a gun’s owner to control the safety-catch using their smartphone or tablet.",
            "In China, 2013, scientists were able to grow a human tooth from scratch using stem cells taken from urine.",
            "French author Thomas-Alexander Dumas (The Three Musketeers) is the highest ranking black military official in Europe to date.",
            "The world record for the largest pineapple was grown in 2011 by Christine McCallum from Bakewell, Australia. The pineapple measured 32cm long and weighed an incredible 8.28kg!",
            "Artist Salvador Dali would often get out of paying for drinks and meals by drawing on the cheques, making them priceless works of art and therefore un-cashable.",
            "Hawaii‘s state flag is the only US state flag to feature the Union Jack upon it.",
            "Surgeons who play video games at least 3 hours a week perform 27% faster and make 37% fewer errors.",
            "There is a blind man in America, Daniel Kish, who uses echolocation to navigate in the same way as a bat! He does this by producing a clicking sound with his tongue and then listening intently for the sound waves to bounce back.",
            "Approximately 1,000,000 dogs in the U.S. are named as the heirs of their owners’ wills.",
            "In an interview with Taylor Swift in 2005, she was told, “If music doesn’t work out, you could be a hair model”. Seven years later, the same woman interviewed her again and apologised for what she said.",
            "When written down, the word ‘almost’ is the longest word in the English language to have all of its letters in alphabetical order.",
            "In Canada, 2012, doctors were able to communicate with a man in a vegetative state. Coma patient Scott Routley was able to tell doctors by using his thoughts that he was not in any pain.",
            "A study was conducted that showed customers in a book-store were 3.48 times more likely to peruse romantic books if the store smelt of chocolate, and 5.93 times more likely to buy them!",
            "Sonic the Hedgehog has registered itself in Guinness Book of World Records for being the fastest gaming character ever.",
            "France has conducted 210 nuclear weapon tests, more than the United Kingdom, China, India, and North Korea combined! This is scarcely a fifth of the amount conducted by the United States, however, who have conducted roughly 1,054 tests.",
            "There is an Australian man, James Harrison, who has a singularly unique blood plasma composition that has been used to cure Rhesus disease, a hemolytic disease that affects newborn babies. He has donated his blood plasma over 1000 times.",
            "In 2011, Chinese surgeons were able to remove the rusty, 4 inch end of a broken blade from the skull of a man who claimed it had been stuck in there for four years! The man had been stabbed in the lower-jaw by a thief four years previously and the blade had snapped off, getting stuck in his head.",
            "Put A Pillow on Your Fridge Day, is celebrated on 29th May in Europe & USA and supposedly brings good luck and wealth to the household.",
            "Nokia was originally founded in 1865 as a paper printing company. Apt, to say when it was founded paper was one of the world’s most used methods of long-distance communication!",
            "Archeologists in London have found a Mesolithic tool-making factory that gives substantial proof human beings were living on the River Thames 7,000 B.C. That’s over 9,000 years ago!",
            "The word ‘oxymoron’ is itself an oxymoron. This is because it derives from Ancient Greek where ‘oxy’ means ‘sharp’ and ‘moros’ means ‘stupid’.",
            "The least financially successful Harry Potter film made approximately $90 million more than the most successful Twilight movie.",
            "In 2007, a 1000-gallon inflatable swimming pool was stolen from someone’s back-garden without a single drop of water being found!",
            "Russia has a larger surface area than Pluto.",
            "Oxford University is older than the Aztec Empire.",
            "If the sun were the size of a white blood cell then the Milky Way Galaxy would be the size of the United States.",
            "here are more stars in space than there are grains of sand on every beach in the world.",
            "For every human on Earth there are 1.6 million ants.",
            "The total weight of all those ants, however, is about the same as all the humans.",
            "On Jupiter and Saturn it rains diamonds.",
            "Your chances of being killed by a vending machine are actually twice as large as your chance of being bitten by a shark.",
            "Nowhere in the Humpty Dumpty Nursery Rhyme does it say that Humpty Dumpty is an egg.",
            "A strawberry is NOT a berry.",
            "A banana IS a berry.",
            "An octopus has three hearts.",
            "There are 10 times more bacteria in your body than actual body cells.",
            "Farting helps reduce high blood pressure and is good for your health.",
            "Breastfeeding allows a baby to give germs to mothers so that her immune system can respond and can synthesize antibodies for her baby.",
            "The boomslang snake’s venom causes you to bleed from all holes of your body.",
            "When getting a new car, choose one that is silver. The color is most visible on the road and is least likely to get into an accident.",
            "By law, a pregnant woman can pee anywhere she wants to in Britain, even if she chooses, in a police officer’s helmets.",
            "The butterflies you get in your stomach when you see someone you like is actually a stress response caused by adrenaline.",
            "A small amount of stress helps you to remember things better but a large amount may hinder your memory.",
            "Most people notice a distinct smell in the air after it rain. That smell after rain is caused by bacteria called actinomycetes.",
            "Our eyes are always the same size from birth, but our nose and ears never stop growing.",
            "Rubbing a banana peel on mosquito bites can help stop the itching.",
            "You don’t sneeze when you are asleep because the nerves involved in the sneeze reflex are also resting.",
            "The colder the room you sleep in, odds are high that you’ll have a bad dream.",
            "Russia didn’t consider beer to be alcohol until 2011. It was previously classified as a soft drink.",
            "To have your photo taken with the first ever camera, you would have to sit still for 8 hours.",
            "Forest fires move faster uphill than downhill.",
            "Scientists claim that the higher your I.Q., the more you dream in your sleep.",
            "Anything a duckling meets 10 minutes after its born becomes its parent.",
            "Flowers are known to grow faster when music plays near them.",
            "The color orange was named after the fruit and not the other way around.",
            "Honey is the only food that included all the substances necessary to sustain life, including enzymes, minerals, water and vitamins.",
            "The Extra Weight Of Obesity Costs Airlines $275 Million Per Year.",
            "Pineapples is not a single fruit, but a group of berries that have fused together.",
            "You can’t hum while holding your nose closed.",
            "Skipping breakfast can cause you to gain weight. This tricks your brain into thinking you want higher-calorie foods later in the day.",
            "Most dust particles in your house are made from dead skin.",
            "Taking nap longer than 20 minutes during day can help boost memory and enhance creativity.",
            "The Facebook Like button was originally planned to be named the Awesome button.",
            "Two-thirds of the people on earth have never seen snow.",
            "Right handed people live, on average, nine years longer than left handed people do.",
            "A humming bird weighs less than a penny.",
            "Fifteen percent of the air you breathe in a metro station is human skin.",
            "Men are 6 times more likely to be struck by lightning than women.",
            "French was the official language of England for over 600 years.",
            "You are more likely to die from a falling coconut than a shark attack.",
            "The average mattress doubles in weight over the course of 10 years due to accumulation of dust mites and dust mite poop.",
            "Earth is the only planet not named after a god.",
            "An ostrich’s eye is bigger than its brain.",
            "The king of hearts is the only king in the standard deck of cards, without a mustache.",
            "If you were to remove all of the empty space from the atoms that make up every human on earth, the entire world population could fit into an apple.",
            "It can take a photon 40,000 years to travel from the core of the sun to the surface, but only 8 minutes to travel the rest of the way to earth.",
            "Spiked dog collars were invented in Ancient Greece to protect dogs throats from wolves!",
            "Drinking a glass of water 30 minutes before a meal helps with your digestive system.",
            "Frogs can suffocate if they hold their mouth open too long.",
            "Whales that sing wrong key get lost and are alone in the ocean.",
            "The harder you concentrate on falling asleep, the less likely to fall asleep.",
            "Crocodiles cannot chew their food.",
            "Horses cannot breathe out their mouths, only their nostrils.",
            "Camel’s milk does not curdle.",
            "A crocodile cannot move its tongue.",
            "Cats have 2 sets of vocal cords: one for purring and one for meowing.",
            "Giraffes have no vocal chords.",
            "Brain waves can be used to power an electric train.",
            "If two pieces of the same type of metal touch in outer space, they will bond together permanently.",
            "Powerful earthquakes can make the Earth spin faster.",
            "All scorpions glow.",
            "Frowning burns more calories than smiling.",
            "More energy from the sun hits Earth every hour than the planet uses in a year.",
            "Penguins have an organ above their eyes that converts seawater to fresh water.",
            "A duck has three eyelids.",
            "Before mercury, brandy was used to fill thermometers.",
            "You would weigh less on the top of a mountain than at sea level.",
            "The infinity sign is called a lemniscate.",
            "Dragonflies capture their prey 95% of the time, making them one of the most efficient predators in nature.",
            "If a wolf is licked out of his pack, he never howls again.",
            "Adult fireflies don’t eat.",
            "Crabs have teeth in their stomach.",
            "Sharks lose a tooth a week.",
            "Only half a dolphin brain falls asleep at a time.",
            "Jellyfish have no heart.",
            "The two animals that can see behind itself without turning its head are the rabbit and the parrot",
            "A female dolphin will assist in the birth of another’s baby dolphin.",
            "Your left lung is smaller than your right lung to make room for your heart.",
            "Human brain is more active during sleep than during the day.",
            "Your most sensitive finger is your index finger.",
            "75 percent of people wash from top to bottom in the shower",
            "Ketchup was originally sold as medicine",
            "Samsung is also a full time weapons manufacturer.They make tanks",
            "In 2006,a man hired a hitman to kill his wife. His wife ended up killing the hitman with her bare hands",
            "A snail can sleep upto three years",
            "Tom Monagphan,the founder of Dominoes pizza met his wife on his first delivery",

    };

    // Method (abilities: things the object can do)
    public String getFact() {
        String fact = "";

        // Randomly select a fact
        Random randomGenerator = new Random(); // Construct a new Random number generator
        int randomNumber = randomGenerator.nextInt(mFacts.length);

        fact = mFacts[randomNumber];

        return fact;
    }
}